name: blockchain-restful-address-index
version: '0.2.0.0'
synopsis: RESTful HTTP "addr-index bitcoind" wrapper
description: See README.md
category: Bitcoin,Web
author: Rune K. Svendsen
maintainer: runesvend@gmail.com
license: OtherLicense
license-file: LICENSE
github: runeksvendsen/blockchain-restful-address-index
dependencies:
- base16-bytestring
- text
- string-conversions
- haskoin-core
- aeson
- servant
- http-api-data
- http-media
- errors
- cereal
- hexstring
- base >=4 && <5
- bitcoin-api
- bitcoin-types
- bitcoin-tx
- base58string
- bytestring
- mtl
- transformers
- configurator
- either
- servant-server
- http-client
- wai
- warp

library:
  source-dirs: src
  ghc-options: -W
  exposed-modules:
  - APISpec.Blockchain
  - APISpec.Types
  #dependencies:

executables:
  rest-addr:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -W
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

